name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install dependencies
        run: npm i

      - name: Build angular app
        run: npm run build -- --prod --base-href /react-packages/

      - name: Copy Index as 404
        run: cp dist/react-packages/index.html dist/react-packages/404.html

      - name: Publish to GH Pages Branch
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist/react-packages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
